services:
  go-chatroom:
    build: .
    container_name: go-chatroom
    networks:
      - web
    volumes:
      - ./chat.log:/app/chat.log
    environment:
      - GIN_DEBUG=release

networks:
  web:
    external: true
